#!/bin/bash

./build/ch_02_03 \
        --batch_size 32 \
        --epochs 10 \
        --resume false \
        --model_path /home/ubuntu/data/foster/ch02_03/model_e10.pt \
        --opt_path /home/ubuntu/data/foster/ch02_03/opt_e10.pt \
        # --trained_model_path /home/ubuntu/data/foster/ch02_03/model_e10.pt \
        # --trained_opt_path /home/ubuntu/data/foster/ch02_03/opt_e10.pt \

